# Generated by Django 6.0.6 on 2026-07-03 14:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0003_alter_mediafile_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychologyTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('category', models.CharField(choices=[('personality', 'شخصیت شناسی'), ('iq', 'هوش و استعداد'), ('academic', 'تحصیلی'), ('psychology', 'روانشناسی'), ('emotional', 'هوش هیجانی')], max_length=50, verbose_name='دسته\u200cبندی')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('coin_price', models.PositiveIntegerField(default=0, verbose_name='قیمت (سکه)')),
                ('duration', models.PositiveIntegerField(default=10, verbose_name='زمان (دقیقه)')),
                ('level', models.CharField(choices=[('simple', 'ساده'), ('medium', 'متوسط'), ('advanced', 'پیشرفته')], default='simple', max_length=20, verbose_name='سطح')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='امتیاز')),
                ('reviews', models.PositiveIntegerField(default=0, verbose_name='تعداد نظرات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psychology_tests', to='storage.mediafile')),
            ],
            options={
                'verbose_name': 'تست روانشناسی',
                'verbose_name_plural': 'تست\u200cهای روانشناسی',
                'db_table': 'psychology_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('abandoned', 'رها شده')], default='in_progress', max_length=20, verbose_name='وضعیت')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(default=0, verbose_name='امتیاز')),
                ('total_questions', models.PositiveIntegerField(default=0, verbose_name='تعداد سوالات')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='psychology_tests.psychologytest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تلاش تست',
                'verbose_name_plural': 'تلاش\u200cهای تست',
                'db_table': 'test_attempts',
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question', models.TextField(verbose_name='سوال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psychology_tests.psychologytest')),
            ],
            options={
                'verbose_name': 'سوال تست',
                'verbose_name_plural': 'سوالات تست',
                'db_table': 'test_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('label', models.CharField(max_length=200, verbose_name='گزینه')),
                ('score', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='psychology_tests.testquestion')),
            ],
            options={
                'verbose_name': 'گزینه سوال',
                'verbose_name_plural': 'گزینه\u200cهای سوال',
                'db_table': 'test_options',
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_correct', models.BooleanField(default=False, verbose_name='پاسخ صحیح')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychology_tests.testattempt')),
                ('selected_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychology_tests.testoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='psychology_tests.testquestion')),
            ],
            options={
                'verbose_name': 'پاسخ تست',
                'verbose_name_plural': 'پاسخ\u200cهای تست',
                'db_table': 'test_answers',
            },
        ),
    ]
