# Generated by Django 6.0.6 on 2026-07-07 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='کد گواهی')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/', verbose_name='فایل گواهی')),
                ('is_verified', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='education.course', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گواهی',
                'verbose_name_plural': 'گواهی\u200cها',
                'db_table': 'certificates',
                'ordering': ['-issued_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
