# Generated by Django 6.0.6 on 2026-07-03 10:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('course_name', models.CharField(max_length=200, verbose_name='نام درس')),
                ('teacher', models.CharField(max_length=150, verbose_name='استاد')),
                ('day', models.CharField(choices=[('شنبه', 'شنبه'), ('یکشنبه', 'یکشنبه'), ('دوشنبه', 'دوشنبه'), ('سه\u200cشنبه', 'سه\u200cشنبه'), ('چهارشنبه', 'چهارشنبه'), ('پنجشنبه', 'پنجشنبه'), ('جمعه', 'جمعه')], max_length=20, verbose_name='روز')),
                ('time_start', models.TimeField(verbose_name='ساعت شروع')),
                ('time_end', models.TimeField(verbose_name='ساعت پایان')),
                ('faculty', models.CharField(max_length=150, verbose_name='دانشکده')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='سالن/کلاس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'برنامه کلاسی',
                'verbose_name_plural': 'برنامه\u200cهای کلاسی',
                'db_table': 'schedule',
                'ordering': ['day', 'time_start', 'order'],
            },
        ),
    ]
