# Generated by Django 6.0.6 on 2026-07-11 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storage', '0003_alter_mediafile_file_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('type', models.CharField(choices=[('discount', 'تخفیف'), ('gift', 'هدیه'), ('voucher', 'اشتراک')], max_length=20, verbose_name='نوع')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('amount', 'مبلغی')], default='percent', max_length=10, verbose_name='نوع تخفیف')),
                ('discount_value', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='مقدار تخفیف')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('expires_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, verbose_name='حداکثر استفاده هر کاربر')),
                ('max_uses_total', models.PositiveIntegerField(default=0, verbose_name='حداکثر استفاده کل')),
                ('applies_to', models.CharField(choices=[('all', 'همه'), ('market', 'فروشگاه'), ('courses', 'دوره\u200cها'), ('books', 'جزوه\u200cها')], default='all', max_length=20, verbose_name='قابل استفاده در')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gifts', to='storage.mediafile')),
                ('users', models.ManyToManyField(blank=True, related_name='assigned_gifts', to=settings.AUTH_USER_MODEL, verbose_name='کاربران خاص')),
            ],
            options={
                'verbose_name': 'هدیه',
                'verbose_name_plural': 'هدایا',
                'db_table': 'gifts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order_id', models.CharField(max_length=100, verbose_name='شناسه سفارش')),
                ('order_type', models.CharField(choices=[('all', 'همه'), ('market', 'فروشگاه'), ('courses', 'دوره\u200cها'), ('books', 'جزوه\u200cها')], max_length=20, verbose_name='نوع سفارش')),
                ('discounted_amount', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ تخفیف')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='gifts.gift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استفاده از هدیه',
                'verbose_name_plural': 'استفاده\u200cهای هدیه',
                'db_table': 'gift_usages',
                'unique_together': {('user', 'gift')},
            },
        ),
    ]
