# Generated by Django 6.0.6 on 2026-07-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiusage',
            name='free_window_started_at',
        ),
        migrations.AddField(
            model_name='aiusage',
            name='last_used_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
