# Generated by Django 6.0.6 on 2026-07-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_aiusage_free_window_started_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusage',
            name='coin_cost_per_message',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
