# Generated by Django 6.0.6 on 2026-07-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_mediafile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
