# Generated by Django 6.0.6 on 2026-07-07 12:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('authority', models.CharField(max_length=100, unique=True, verbose_name='شناسه مرجع')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق'), ('refunded', 'برگشت خورده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('card_pan', models.CharField(blank=True, max_length=20, verbose_name='شماره کارت')),
                ('card_hash', models.CharField(blank=True, max_length=100, verbose_name='هش کارت')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
