# Generated by Django 6.0.6 on 2026-07-03 07:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='چسبیده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'db_table': 'announcements',
                'ordering': ['-is_pinned', '-date'],
            },
        ),
    ]
