# Generated by Django 6.0.6 on 2026-07-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='reason',
            field=models.CharField(choices=[('purchase', 'خرید سکه با پول'), ('course_enrollment', 'ثبت\u200cنام در دوره'), ('refund', 'بازگشت سکه'), ('admin_adjustment', 'تغییر توسط ادمین'), ('convert_from_wallet', 'تبدیل از کیف پول'), ('sell_note', 'فروش جزوه'), ('download_note', 'دانلود جزوه'), ('ai_chat', 'مکالمه با هوش مصنوعی')], max_length=30),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='type',
            field=models.CharField(choices=[('credit', 'افزایش'), ('debit', 'کاهش')], max_length=20),
        ),
    ]
