# Generated by Django 6.0.6 on 2026-07-03 07:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('prize', models.CharField(max_length=200, verbose_name='جایزه')),
                ('deadline', models.DateTimeField(verbose_name='مهلت ثبت نام')),
                ('status', models.CharField(choices=[('active', 'در حال برگزاری'), ('upcoming', 'به زودی'), ('ended', 'پایان یافته')], default='upcoming', max_length=20, verbose_name='وضعیت')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='تعداد شرکت\u200cکنندگان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مسابقه',
                'verbose_name_plural': 'مسابقات',
                'db_table': 'competitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='competitions.competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ثبت نام مسابقه',
                'verbose_name_plural': 'ثبت نام\u200cهای مسابقات',
                'db_table': 'competition_registrations',
                'unique_together': {('user', 'competition')},
            },
        ),
    ]
