# Generated by Django 6.0.6 on 2026-07-10 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='banners/%Y/%m/%d/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('placement', models.CharField(choices=[('home_top', 'بالای صفحه اصلی'), ('home_middle', 'وسط صفحه اصلی'), ('course_page', 'صفحه دوره')], default='home_top', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنرها',
                'db_table': 'banners',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active'], name='banners_placeme_c011a9_idx'), models.Index(fields=['order'], name='banners_order_f729fe_idx')],
            },
        ),
    ]
