# Generated by Django 6.0.6 on 2026-07-06 15:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'db_table': 'question_categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='مدرس')),
                ('price_type', models.CharField(choices=[('free', 'رایگان'), ('paid', 'پولی')], default='free', max_length=10, verbose_name='نوع قیمت')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('file', models.FileField(upload_to='question_bank/%Y/%m/%d/', verbose_name='فایل')),
                ('file_name', models.CharField(max_length=255, verbose_name='نام فایل')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل')),
                ('file_mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع فایل')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='دانلود')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='لایک')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='question_bank.category', verbose_name='دسته\u200cبندی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('coins_spent', models.PositiveIntegerField(default=0, verbose_name='سکه مصرف شده')),
                ('is_first_download', models.BooleanField(default=True, verbose_name='اولین دانلود')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان دانلود')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads_log', to='question_bank.question', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_downloads', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دانلود سوال',
                'verbose_name_plural': 'دانلودهای سوالات',
                'db_table': 'question_downloads',
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_log', to='question_bank.question', verbose_name='سوال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لایک سوال',
                'verbose_name_plural': 'لایک\u200cهای سوالات',
                'db_table': 'question_likes',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
