# Generated by Django 6.0.6 on 2026-07-08 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='purchased_by',
            field=models.ManyToManyField(blank=True, help_text='کاربرانی که این سوال را خریداری کرده\u200cاند', related_name='purchased_questions', to=settings.AUTH_USER_MODEL, verbose_name='خریداری شده توسط'),
        ),
    ]
