# Generated by Django 6.0.6 on 2026-07-03 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('mobile', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('read', 'خوانده شده'), ('replied', 'پاسخ داده شده')], default='pending', max_length=20, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
