# Generated by Django 6.0.6 on 2026-07-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'شارژ'), ('withdrawal', 'برداشت'), ('payout', 'پرداخت به فروشنده'), ('transfer', 'انتقال'), ('refund', 'بازگشت وجه'), ('fee', 'کارمزد')], max_length=20),
        ),
    ]
